### ISSUE TITLE
Supporting testnets

### ISSUE THREAD

**Issue by Marxpark** [lidofinance/ledgerhq-frame-connector#1]
I'm having difficulties to easily test this on testnetworks.
I think activate should always return a chainId aswell
I also think that the config should be able to take an array of supported networks. I might just be missinterpreting it all, but i think mainnet is coded and passed to super constructor?

**Comment by alx-khramov** [comment]
@Marxpark Hey! You are right, mainnet is hardcoded for now. We are going to move this package to be a part of our new wallets-related library, and it is going to be refactored a bit. I will consider making chain id not hardcoded. It is going to happen relatively soon, but I can't give you a more accurate estimation, sorry.

**Comment by Jeday** [comment]
We added support for testnets in latest update. But from now on this package will be part of wallet library. This is the last update I suppose.

**Comment by alx-khramov** [comment]
Moved into reef-knot: https://github.com/lidofinance/reef-knot/pull/62
